
server:
  port: 8080
  servlet:
    context-path: /
  server:
    connectionTimeout: 180000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/studentunion?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    password: admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true

mybatis:
  type-aliases-package: com.test.shiro.entity
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com:
      taru:
        houseapp:
          dao: DEBUG
          controller: INFO
  file:
    path: logs



pagehelper:
  helper-dialect=mysql: mysql
  reasonable: false
  support-methods-arguments: true



